Repository artichoke/intaglio, pull requests merged in 2020-07, with the labels that each got.

#22 Replace doc_comment dev-dependency with a small inlined macro_rules macro
  Cargo.toml
  src/lib.rs
Labels: A-build, A-deps

#23 Move criterion benchmarks into a private subcrate
  .github/workflows/bench.yaml
  Cargo.toml
  benchmarks/.gitignore
  benchmarks/Cargo.toml
  benchmarks/benches/benchmarks.rs
  benchmarks/src/lib.rs
  src/lib.rs
Labels: A-build, A-deps, A-performance

#24 Use an anonymous constant for static assertions
  src/lib.rs
Labels: A-bytestring-interner, A-utf8-string-interner, C-quality

#25 API refinements
  src/lib.rs
Labels: A-performance, A-release, C-quality

#26 Improve crate rustdocs
  src/bytes.rs
  src/lib.rs
  src/str.rs
Labels: A-release, C-docs, C-quality

#27 Bump version to v1.1.0
  Cargo.toml
  README.md
  src/lib.rs
Labels: A-release

#28 Reduce unsafe usage
  src/bytes.rs
  src/str.rs
Labels: A-security, A-utf8-string-interner, S-speculative

#29 Update docs to remove references to `Box::leak` and reimplement Debug for bytes interner
  Cargo.toml
  README.md
  src/bytes.rs
  src/internal.rs
  src/lib.rs
  src/str.rs
Labels: A-bytestring-interner, A-utf8-string-interner, C-bug

#30 Improvements to internal data structures
  src/bytes.rs
  src/internal.rs
  src/str.rs
Labels: A-performance, C-docs, C-quality

#31 Tweak safety docs for Interned::as_static_slice
  src/internal.rs
Labels: C-docs

#32 Simplify debug reprs of Slice internals
  src/internal.rs
Labels: A-bytestring-interner, A-utf8-string-interner, C-quality

#33 Rename clippy::identity_conversion lint allow
  tests/leak/mod.rs
Labels: A-build, C-quality
